In [1]:
import numpy as np

In [8]:
labels = np.load('outputs/labels.npy')

In [9]:
labels

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [7, 7, 7, ..., 7, 7, 7],
       [7, 7, 7, ..., 7, 7, 7],
       [7, 7, 7, ..., 7, 7, 7]])

In [11]:
np.unique(labels)

array([ 0,  7, 15])

In [12]:
labels.shape

(341, 512)

In [13]:
labels3 = np.load('outputs/labels3.npy')
np.unique(labels3)

array([ 0, 13, 15])